### PR TITLE
perf(Dependencies): removes unused dependencies

### PR DESCRIPTION
**Pull request by rapahaeru**
## Description
 removes unused dependencies

## Setup
to view the components behavior, run `yarn storybook`

## Review guide
- [ ] Unit tests (yarn test:components)
- [ ] Regression \
      - first start the storybook for regression tests(and keep it open): ` yarn test:regression:storybook`; \
      - then run the regression tests: `yarn test:regression`
- [ ] Code review

### Browsers review
- [ ] Layout review
  - [ ] Edge
  - [ ] Firefox
  - [ ] Chrome
  - [ ] Safari
  - [ ] Mobile
- [ ] Ux review validation

### CODE REVIEW

**Review by MarcosViniciusPC — APPROVED** [review]
[x] Code review
[x] Unit
[x] Regression
[x] Build

**Review by MarcosViniciusPC — COMMENTED** [review]
No problems with removing the libs. However, I checked other libs that can be removed. Does it make sense for them to be removed at this point? Below is the list of libs that apparently can be removed.

"babel-jest": "^24.0.0",
"dotenv-webpack": "^1.6.0",
"istanbul": "^0.4.5",
"jest-diff": "^24.0.0",
"react-cookies": "^0.1.0",
"strip-ansi": "^5.0.0",
"core-js": "2.5.7"

**Comment by rapahaeru** [comment]
the libs listed below are not present in the package

"jest-diff": "^24.0.0",
"core-js": "2.5.7"
"istanbul": "^0.4.5",

**Review by MarcosViniciusPC — APPROVED** [review]
[x] Code review
[x] Unit
[x] Regression
[x] Doc
[x] Build

**Review by alizeleal — APPROVED** [review]
[x] Unit
[x] Regression
[x] Build
[x] Layout review

**Review by alizeleal — APPROVED** [review]

**Review by 2bfe26 — APPROVED** [review]

**Pull request merged**
