### PR TITLE
fix(Input): removes close icon for disabled inputs

### PR DESCRIPTION
**Pull request by rapahaeru**
## Description
https://jirasoftware.catho.com.br/browse/QTM-207

## Setup
to view the components behavior, run `yarn storybook`

## Review guide
- [ ] Coverage (coverage status should not regress)\
      - `yarn test:coverage`
- [ ] Unit tests (yarn test:components)
- [ ] Regression \
      - first start the storybook for regression tests(and keep it open): ` yarn test:regression:storybook`; \
      - then run the regression tests: `yarn test:regression`
- [ ] Code review

### Browsers review
- [ ] Layout review
  - [ ] Edge
  - [ ] Firefox
  - [ ] Chrome
  - [ ] Safari
  - [ ] Mobile
- [ ] Ux review validation

### CODE REVIEW

**Review by rodrigoclemente — APPROVED** [review]

**Comment by tcelestino** [comment]
@rapahaeru, running `yarn test:coverage` show me this:

Screenshot from 2020-09-03 14-19-28

Running `yarn test -u`, this error happened: 

Screenshot from 2020-09-03 14-21-10

**Review by tcelestino — APPROVED** [review]
## Review guide
- [x] Coverage (coverage status should not regress)\
      - `yarn test:coverage`
- [x] Unit tests (yarn test:components)
- [x] Regression \
      - first start the storybook for regression tests(and keep it open): ` yarn test:regression:storybook`; \
      - then run the regression tests: `yarn test:regression`
- [x] Code review

### Browsers review
- [x] Layout review
  - [ ] Edge
  - [x] Firefox
  - [x] Chrome
  - [ ] Safari
  - [x] Mobile
- [x] Ux review validation

**Review by pedrosouza — APPROVED** [review]
## Review guide
- [x] Coverage (coverage status should not regress)\
      - `yarn test:coverage`
- [x] Unit tests (yarn test:components)
- [x] Regression \
      - first start the storybook for regression tests(and keep it open): ` yarn test:regression:storybook`; \
      - then run the regression tests: `yarn test:regression`
- [x] Code review

### Browsers review
- [x] Layout review
  - [x] Edge
  - [x] Firefox
  - [x] Chrome
  - [x] Safari
  - [x] Mobile

**Pull request merged**
