### PR TITLE
chore(Storybook): updates quantum-storybook-ui

### PR DESCRIPTION
**Pull request by rapahaeru**
## Description
Updates quantum-storybook-ui newer version.

## Setup
to view the components behavior, run `yarn storybook`

## Review guide
- [ ] Code review
- [ ] simulates storybook

### CODE REVIEW

**Review by pedrosouza — DISMISSED** [review]
## Review guide
- [x] Code review
- [x] simulates storybook

**Review by pedrosouza — APPROVED** [review]
## Review guide
- [x] Code review
- [x] simulates storybook

**Review by tcelestino — APPROVED** [review]
## Review guide
- [x] Code review
- [x] simulates storybook

**Pull request merged**
