### PR TITLE
Adding a componentWillReceiveProps update for the <Input> component

### PR DESCRIPTION
**Pull request by Agezao**
Suggestion to fix catho/quantum#197

### CODE REVIEW

**Comment by Agezao** [comment]
Hello @rapahaeru!

I've updated the PR with a commit changing `componentWillReceiveProps` to `getDerivedStateFromProps`, as the react docs suggest given the deprecation of `componentWillReceiveProps` in upcoming releases;

I've tested the code with the following:

```
import React, { Component } from "react";

import { Input as QuantumInput } from "@catho/quantum";
import { Input as ChangedInput } from "@age/quantum";

class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      text: ""
    };
  }

  handleSubmit(e) {
    e.preventDefault();

    this.setState({ text: "" });
  }

  handleChange(e) {
    this.setState({ text: e.target.value })
  }

  render() {
    return (
      <div>
        <h1>Quantum Form Test</h1>
        <form onSubmit={(e) => this.handleSubmit(e)}>
          <div>
            <small>@catho/quantum</small> <br />

            <QuantumInput
              value={this.state.text}
              onChange={e => this.handleChange(e)}
            />
          </div>

          <hr />

          <div>
            <small>@age/quantum</small> <br />

            <ChangedInput
              value={this.state.text}
              onChange={e => this.handleChange(e)}
            />
          </div>

          <hr />

          <button>Clean</button>
        </form>
      </div>
    );
  }
}

export default App;
```

And apparently everything went well this time. No errors nor warnings. Can you please re-test it and double-check the changes? :)

Thanks!!

**Comment by renatogalvones** [comment]
Hey @Agezao !

I've tested your code here, and the native(inside input) "clear" button stopped working on your example. Was it expected to behave like that?
I believe ideally both ways should work.

**Comment by Agezao** [comment]
This is probably a side-effect of the state being controlled by the `App` component and I've not bound anything to the `onClean` event in order to communicate this change to the `App` component state;

With the event being implemented, this behavior doesn't persists:

```
import React, { Component } from "react";
import {
  Input as QuantumInput,
  Form,
  GlobalStyle
} from "@catho/quantum";
import { Input as ChangedInput } from "@age/quantum";

class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      text: ""
    };
  }

  handleSubmit(e) {
    e.preventDefault();

    this.setState({ text: "" });
  }

  handleChange(e) {
    this.setState({ text: e.target.value })
  }

  handleClean(e) {
    this.setState({ text: '' })
  }

  render() {
    return (
      <div>
        <GlobalStyle />
        <h1>Quantum Form Test</h1>
        <Form onSubmit={(e) => this.handleSubmit(e)}>
          <div>
            <small>@catho/quantum</small> <br />

            <QuantumInput
              value={this.state.text}
              onChange={e => this.handleChange(e)}
              onClean={e => this.handleClean(e)}
            />
          </div>

          <hr />

          <div>
            <small>@age/quantum</small> <br />

            <ChangedInput
              value={this.state.text}
              onChange={e => this.handleChange(e)}
              onClean={e => this.handleClean(e)}
            />
          </div>

          <hr />

          <button>Clean</button>
        </Form>
      </div>
    );
  }
}
```

**Comment by rapahaeru** [comment]
We (@Agezao and i) simulate locally and it was found that PR does not resolves the problem.
We need to fix the nested childs Form before, to apply this changes.
Thanks for the pair @Agezao .

**Pull request closed without merging**
